### ISSUE TITLE
hello thanks for the code

### ISSUE THREAD

**Issue by MightyTedKim** [scrapehero/walmart_store_locator#1]
hello thanks for the code
I'vce put some prints in the code to check where i am
and think  writer.writeheader() part is the problem.
can give me a tip how to go through this propblem?

thanks

start
main.py __name__: __main__
retrieving stores
retry:  0
processing store details
Writing scraped data to 20005_stores.csv
writer: <csv.DictWriter object at 0x000001CCC3B55B70>
Traceback (most recent call last):
  File "walmart_store_locator.py", line 77, in <module>
    writer.writeheader()
  File "C:\ProgramData\Anaconda3\lib\csv.py", line 144, in writeheader
    self.writerow(header)
  File "C:\ProgramData\Anaconda3\lib\csv.py", line 155, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
TypeError: a bytes-like object is required, not 'str'

**Comment by MightyTedKim** [comment]
ah sorry I stackoverflowed

changing wb to w
        with open('%s_stores.csv' % (zip_code), 'w') as csvfile:

was using python 3

https://stackoverflow.com/questions/34283178/typeerror-a-bytes-like-object-is-required-not-str-in-python-and-csv
